### ISSUE TITLE
Design Message Inbox 

### ISSUE THREAD

**Issue by manavsiddharthgupta** [bottercode/DevGram#29]
Make UX/UI similar to Twitter Message Inbox -> 

<img width="355" alt="test" src="https://user-images.githubusercontent.com/79929708/231661517-d542df2c-2b9e-47f7-ab13-06181df9c89f.png">

**Comment by bottercode** [comment]
![image](https://user-images.githubusercontent.com/74648201/232122594-908cc8ee-a4d2-462e-9ef6-b6bfd4cab10a.png)
how about this? Just made a design

**Comment by manavsiddharthgupta** [comment]
#34 Message UI components pr is merged however it's not completed, we gonna accept pr related to the message component but the issue will be closed for now.
