### ISSUE TITLE
Create a Navbar For HomePage 

### ISSUE THREAD

**Issue by manavsiddharthgupta** [bottercode/DevGram#7]
Create a navbar for Home Page 
Example: 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/79929708/230739756-8a0570fe-31d3-4795-b577-65fdea6d09f6.png">
and, yes content will be different u can take inspiration from anywhere.

**Comment by bottercode** [comment]
@skgx work on this.

**Comment by skgx** [comment]
Sure
